### ISSUE TITLE
Not working with https?

### ISSUE THREAD

**Issue by mjmasn** [meteorhacks/meteor-down#15]
I can't seem to get this to work over a https connection... any thoughts?

The error I get is:

```
undefined:1
<html><body><h1>503 Service Unavailable</h1>
^
SyntaxError: Unexpected token <
  at Object.parse (native)
  at Request._callback (/Users/mike/.nvm/versions/node/v0.12.0/lib/node_modules/meteor-down/node_modules/ddp/lib/ddp-client.js:336:23)
  at Request.self.callback (/Users/mike/.nvm/versions/node/v0.12.0/lib/node_modules/meteor-down/node_modules/ddp/node_modules/request/request.js:344:22)
  at Request.emit (events.js:110:17)
  at Request.<anonymous> (/Users/mike/.nvm/versions/node/v0.12.0/lib/node_modules/meteor-down/node_modules/ddp/node_modules/request/request.js:1239:14)
  at Request.emit (events.js:129:20)
  at IncomingMessage.<anonymous> (/Users/mike/.nvm/versions/node/v0.12.0/lib/node_modules/meteor-down/node_modules/ddp/node_modules/request/request.js:1187:12)
  at IncomingMessage.emit (events.js:129:20)
  at _stream_readable.js:908:16
  at process._tickCallback (node.js:355:11)

```

**Comment by mjmasn** [comment]
@arunoda any ideas?

**Comment by francojfernandez** [comment]
+1

**Comment by louis49** [comment]
Try this PR : https://github.com/meteorhacks/meteor-down/pull/20
Working for me.

**Comment by tzapu** [comment]
hi,

i was able to test over https with this bit
```
meteorDown.init(function (Meteor) {
  Meteor.call('addClient', { id: 'newClient', apiKey: '7schWTAcWZQ5NkHt' }, function (error, result) {
    Meteor.kill();
  });
});
meteorDown.run({
  concurrency: 600,
  url: 'https://domain.com',
  ssl: true,
});


```

hope it helps
