### ISSUE TITLE
Login Error Internal server error [500]

### ISSUE THREAD

**Issue by Here21** [meteorhacks/meteor-down#22]
hi, this is Martin, I need some help, I think meteor-down core version is too low
```
meteorDown.init(function (Meteor) {
  Meteor.subscribe('documents', function () {
    console.log('Subscription is ready');
    console.log(Meteor.collections.items);
    Meteor.kill();
  });
    // console.log("userId is:", Meteor.userId());
});
meteorDown.run({
  concurrency: 10,
  url: "http://localhost:3000",
  key: 'martinloadtest',
  auth: {userIds: ['YNc8bLy4tuFto4J7Q']}
})
```

```
I20170623-18:42:11.345(8)?     at packages/ddp-server/livedata_server.js:715:46
I20170623-18:42:11.346(8)? Exception while invoking method 'MeteorDown:login' ReferenceError: check is not defined
I20170623-18:42:11.346(8)?     at [object Object].Meteor.methods.MeteorDown:login (packages/meteorhacks_meteor-down.js:31:5)
I20170623-18:42:11.346(8)?     at packages/check.js:129:16
I20170623-18:42:11.347(8)?     at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
I20170623-18:42:11.360(8)?     at Object.exports.Match._failIfArgumentsAreNotAllChecked (packages/check.js:128:41)
I20170623-18:42:11.361(8)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1734:18)
I20170623-18:42:11.361(8)?     at packages/ddp-server/livedata_server.js:719:19
I20170623-18:42:11.362(8)?     at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
I20170623-18:42:11.362(8)?     at packages/ddp-server/livedata_server.js:717:40
I20170623-18:42:11.362(8)?     at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
I20170623-18:42:11.363(8)?     at packages/ddp-server/livedata_server.js:715:46
```

```
▶ meteor-down load_test.js
(node:93074) DeprecationWarning: 'GLOBAL' is deprecated, use 'global'
(node:93074) DeprecationWarning: 'root' is deprecated, use 'global'
/Users/simon/.nvm/versions/node/v6.9.2/lib/node_modules/meteor-down/lib/mdown.js:47
    if(error) throw error;
              ^

Error: Login Error Internal server error [500]
  at /Users/simon/.nvm/versions/node/v6.9.2/lib/node_modules/meteor-down/lib/client.js:107:15
  at Client.DDPClient._message (/Users/simon/.nvm/versions/node/v6.9.2/lib/node_modules/meteor-down/node_modules/ddp/lib/ddp-client.js:147:7)
  at Client.<anonymous> (/Users/simon/.nvm/versions/node/v6.9.2/lib/node_modules/meteor-down/node_modules/ddp/lib/ddp-client.js:87:10)
  at emitOne (events.js:96:13)
  at Client.emit (events.js:188:7)
  at Client.dispatchEvent (/Users/simon/.nvm/versions/node/v6.9.2/lib/node_modules/meteor-down/node_modules/faye-websocket/lib/faye/websocket/api/event_target.js:24:10)
  at Client._receiveMessage (/Users/simon/.nvm/versions/node/v6.9.2/lib/node_modules/meteor-down/node_modules/faye-websocket/lib/faye/websocket/api.js:123:10)
  at Client.<anonymous> (/Users/simon/.nvm/versions/node/v6.9.2/lib/node_modules/meteor-down/node_modules/faye-websocket/lib/faye/websocket/api.js:41:49)
  at emitOne (events.js:101:20)
  at Client.emit (events.js:188:7)
  at Client.<anonymous> (/Users/simon/.nvm/versions/node/v6.9.2/lib/node_modules/meteor-down/node_modules/websocket-driver/lib/websocket/driver/hybi.js:451:14)
  at pipe (/Users/simon/.nvm/versions/node/v6.9.2/lib/node_modules/meteor-down/node_modules/websocket-extensions/lib/pipeline/index.js:37:40)
  at Pipeline._loop (/Users/simon/.nvm/versions/node/v6.9.2/lib/node_modules/meteor-down/node_modules/websocket-extensions/lib/pipeline/index.js:44:3)
  at Pipeline.processIncomingMessage (/Users/simon/.nvm/versions/node/v6.9.2/lib/node_modules/meteor-down/node_modules/websocket-extensions/lib/pipeline/index.js:13:8)
  at Extensions.processIncomingMessage (/Users/simon/.nvm/versions/node/v6.9.2/lib/node_modules/meteor-down/node_modules/websocket-extensions/lib/websocket_extensions.js:133:20)
  at Client._emitMessage (/Users/simon/.nvm/versions/node/v6.9.2/lib/node_modules/meteor-down/node_modules/websocket-driver/lib/websocket/driver/hybi.js:442:22)
  at Client._emitFrame (/Users/simon/.nvm/versions/node/v6.9.2/lib/node_modules/meteor-down/node_modules/websocket-driver/lib/websocket/driver/hybi.js:405:19)
  at Client.parse (/Users/simon/.nvm/versions/node/v6.9.2/lib/node_modules/meteor-down/node_modules/websocket-driver/lib/websocket/driver/hybi.js:141:18)
  at Client.parse (/Users/simon/.nvm/versions/node/v6.9.2/lib/node_modules/meteor-down/node_modules/websocket-driver/lib/websocket/driver/client.js:62:58)
  at IO.write (/Users/simon/.nvm/versions/node/v6.9.2/lib/node_modules/meteor-down/node_modules/websocket-driver/lib/websocket/streams.js:80:16)
  at Socket.ondata (_stream_readable.js:555:20)
  at emitOne (events.js:96:13)
  at Socket.emit (events.js:188:7)
  at readableAddChunk (_stream_readable.js:176:18)
  at Socket.Readable.push (_stream_readable.js:134:10)
  at TCP.onread (net.js:548:20)
```

**Comment by vinaynb** [comment]
Facing same issue. @mnmtanish any help ?

**Comment by vinaynb** [comment]
I do not know if this the right way to fix this but the error goes away by installing following two packages
```
meteor add check
meteor add ejson
```

**Comment by crapthings** [comment]
@vinaynb doesn't work for now

**Comment by crapthings** [comment]
https://github.com/meteorhacks/meteor-down-backdoor/blob/master/lib/meteor-down.js#L24

for someone who has same error

change this line to 

```js
var session = Meteor.server.sessions.get(sessionId);
```

and upgrade meteor-down's ddp to

```
"ddp": "0.12.1",
```
